### ISSUE TITLE
tbd > dylib

### ISSUE THREAD

**Issue by iThanh** [Siguza/tbdump#1]
Thank you for your sharing.
But can I convert back tbd to dylib, please?

**Comment by Siguza** [comment]
Haha, no.  
A .tbd is only the list of symbols a .dylib contains. You can't magically make reconstruct code out of that.

**Comment by iThanh** [comment]
So, can I read all symbols all .tbd, please?

**Comment by Siguza** [comment]
Open them in a text editor?

**Comment by iThanh** [comment]
Thank you!
